name: Deploy Backend Files to MongoDB

on:
  push:
    branches:
      - cloudadda

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @octokit/rest mongodb

      - name: Deploy to MongoDB
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          CONNECT_GITHUB: ${{ secrets.CONNECT_GITHUB }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: node deploy_script.mjs